version: '3.8'

services:
  whatsapp-service:
    environment:
      - PUPPETEER_WS_ENDPOINT=ws://chrome:3000
    depends_on:
      - chrome

  chrome:
    image: browserless/chrome:latest
    environment:
      - CONNECTION_TIMEOUT=604800000  # 7 dias em milissegundos
      - KEEP_ALIVE=true
      - CHROME_REFRESH_TIME=604800000  # Também 7 dias
      - DEFAULT_BLOCK_ADS=true
      - ENABLE_CORS=true
      - PREBOOT_CHROME=true  # Pré-carrega o Chrome para melhor estabilidade
      - MAX_CONCURRENT_SESSIONS=5  # Limita o número de sessões concorrentes
      - MAX_QUEUE_LENGTH=10  # Limitar tamanho da fila de requisições
      - CHROME_PATH=/usr/bin/google-chrome
      - DEFAULT_LAUNCH_ARGS=["--no-sandbox", "--disable-setuid-sandbox", "--disable-dev-shm-usage", "--disable-accelerated-2d-canvas", "--disable-gpu", "--disable-notifications", "--disable-extensions", "--disable-sync", "--window-size=1280,720", "--mute-audio", "--hide-scrollbars", "--disable-background-networking", "--js-flags=--expose-gc", "--disable-features=site-per-process"]
    ports:
      - "9222:3000"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G  # Aumentado de 6G para 8G
        reservations:
          cpus: '1'
          memory: 3G  # Aumentado para melhorar a estabilidade
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3